version: '3'
services:
  web:
    image: voidxnull/zeropool-console
    build: .
    container_name: zeropool-console
    restart: always
    ports:
      - "80:80"
    environment:
      EVM_RPC: ${EVM_RPC}
      RELAYER_URL: ${RELAYER_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      TOKEN_ADDRESS: ${TOKEN_ADDRESS}
